zucchini/zucchini

setup.py
Easier to type because the h confuses people, including me!
Please lmk if this breaks other stuff
=> setup.py: Make binary zucc, not zucchini

tests/test_zucchini.py, zucchini/backend.py, zucchini/cli.py
=> Add subcommand stubs

setup.py, zucchini/assignment.py, zucchini/cli.py, zucchini/graders/__init__.py, zucchini/graders/grader_interface.py, zucchini/graders/libcheck_grader.py, zucchini/graders/open_file_grader.py, zucchini/graders/prompt_grader.py, zucchini/graders/threaded_grader.py, zucchini/grades.py, zucchini/grading_manager.py, zucchini/submission.py, zucchini/utils.py
Write part grades to the `meta.json` of each submission, implement grade calculation logic, and use it to display calculated grades after grading
Also support exporting grades to a CSV and canvas
=> Introduce parts, display submission grades after grading, basic exporting, libcheck backend

README.rst
If we want people to work on this, we need instructions haha
=> README: Add getting started instructions

zucchini/canvas.py, zucchini/cli.py, zucchini/submission.py
When testing against homework 1, I found some interesting Canvas API
quirks:
1. When a student does not submit an assignment, the assignment date is
null
2. Non-admins cannot GET /user/
3. When a submission has no attachments, there is simply no attachments
array
=> Account for Canvas API quirks

zucchini/graders/__init__.py, zucchini/graders/junit_grader.py, zucchini/graders/junit_json_grader.py
Support the JUnit+JSON grader Patrick magicked up
=> Add support for homework 1 grader

zucchini/assignment.py, zucchini/submission.py
=> Allow optional files for an assignment component

zucchini/assignment.py, zucchini/canvas.py, zucchini/cli.py, zucchini/grading_manager.py, zucchini/penalizers/__init__.py, zucchini/penalizers/exceptions.py, zucchini/penalizers/late_penalizer.py, zucchini/penalizers/penalizer_interface.py, zucchini/submission.py
Instead of hardcoding late penalties, try to generalize the concept of penalties, and include an implementation which penalizes for late submissions
=> Add late penalites via a Penalizer framework

zucchini/flatten.py
Hack to get homework 1 out the door, heck yea
=> flatten: Allow archives up to 64 MiB

zucchini/submission.py
Pretty-print meta.json so that humans can actually read it.
=> Make meta.json more readable

zucchini/cli.py, zucchini/filter.py, zucchini/grading_manager.py
=> Filter submissions to load/export/grade

zucchini/assignment.py, zucchini/cli.py, zucchini/graders/junit_xml_grader.py, zucchini/graders/threaded_grader.py, zucchini/grading_manager.py, zucchini/utils.py
=> Attempt putting noninteractive components in own thread

zucchini/graders/__init__.py, zucchini/graders/bitwise_json_grader.py, zucchini/grading_manager.py
at last!
patrick, I had to change the hash function used to generate the student id for the grade logs because sha3-224 isn't in python until 3.6, which is pretty recent. that ok?
=> Support Homework 2

zucchini/cli.py, zucchini/loaders/__init__.py, zucchini/loaders/gradescope_loader.py
frickin raw vegan bay area yoga software
=> Add basic gradescope loader

zucchini/cli.py, zucchini/graders/__init__.py, zucchini/graders/command_grader.py, zucchini/grading_manager.py, zucchini/loaders/__init__.py, zucchini/loaders/canvas_archive_loader.py
both easier and harder than i thought cool
=> Support grading timed lab 5

zucchini/graders/__init__.py, zucchini/graders/circuitsim_grader.py
For https://github.com/ausbin/circuitsim-grader-template/
I realize we want to limit backends like this, but until we standardize some format... yea
=> Add CircuitSim backend

zucchini/assignment.py, zucchini/cli.py, zucchini/grading_manager.py, zucchini/submission.py
Add `zucc grade-submission x/y/z`, which will grade the submission at `x/y/z` and output the component grades json to stdout
=> Grade single submission

zucchini/zucchini.py
=> Revert tragic loss of farms (RIP)

zucchini/cli.py, zucchini/submission.py
=> Add manual loader

zucchini/graders/circuitsim_grader.py
ausbin/circuitsim-grader-template@17e7834950f0c8fd8bc3cacdb65e0c9ef10fe9c0 makes a breaking change the output format
=> CircuitSim backend: Support new abbreviated test result format

zucchini/assignment.py, zucchini/cli.py, zucchini/gradescope.py, zucchini/grading_manager.py
Make grades out of the total Gradescope points, not 100.
=> Add first stab at Gradescope total points

zucchini/gradescope.py
One line.
Several confused students.
Two thousand one hundred ten.
=> Flatten Gradescope submissions

zucchini/cli.py, zucchini/gradescope.py, zucchini/penalizers/__init__.py, zucchini/penalizers/checkoff_penalizer.py
Goal is to cross reference the submission name with the list of students who have been checked off for attendance. This way, when a student is checked off during a Timed Lab, any submission after that will automatically give them a 0. 
I've never really used python, so any stylistic comments would be greatly appreciated.
=> Initial draft of a checkoff penalizer. 

zucchini/graders/__init__.py, zucchini/graders/python_module_grader.py
Example zucchini assignment:
[module-test-example.tar.gz](https://github.com/zucchini/zucchini/files/3594624/module-test-example.tar.gz)
=> Add basic glue between Sam's K-Map grader and zucchini

setup.cfg, setup.py, zucchini/__init__.py, zucchini/gradescope.py
I can't believe I literally reviewed my own code and pointed this out: https://github.com/zucchini/zucchini/pull/641#discussion_r1398327740. I need intensive Louisville Slugger cranial therapy
=> Fix stupid bug from #641
